---
- host: all
  become: true

  tasks:
  - name: update apt
    command: sudo apt update

  - name: install docker engine
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy php application
    command: docker run -itd -p 8081:8080 sachinrathee/webapp:v1.0