---
- hosts: server
  become: true

  tasks:
  - name: update apt
    command: sudo apt update

  - name: install docker engine
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: delete existing container
    command: docker rm -f webapp

  - name: deploy php application
    command: docker run -itd --name webapp -p 8081:80 sachinrathee/php-webapp:latest
